### ISSUE TITLE
Possible Feature Request on date based badge.

### ISSUE THREAD

**Issue by reefland** [kashalls/kromgo#108]
My cluster age is getting pretty high:

![Image](https://github.com/user-attachments/assets/b1f85930-db06-4ea5-a5db-459fd0d0a19f)

I'd like to show that in a format more like `3y63d`, is this possible?

**Comment by kashalls** [comment]
This should be possible, although I am not sure how I would properly implement this. I might be open to doing some kind of go templating? I am sure there would be something good here, but I am not sure.

**Comment by kashalls** [comment]
@reefland Would adding support for go templating for each section possibly resolve this?

**Comment by reefland** [comment]
Not sure, do you have an example of what that might look like?  

I think in terms of bash like:
```
$ cat time-test.sh

#!/bin/bash

days="$1"
years=$(( days / 365 ))
rem_days=$(( days % 365 ))
echo "${years}y${rem_days}d"

$ bash time-test.sh 1159
3y64d
```

And if this is what I have now for kromgo:
```
          - name: cluster_age_days
            query: round((time() - min(kube_node_created)) / 86400)
            suffix: "d"
            colors:
              - { color: "#ADFF2F", min: 0, max: 180 } # GreenYellow
              - { color: "#32CD32", min: 181, max: 360 } # LimeGreen
              - { color: "#2E8B57", min: 361, max: 720 } # SeaGreen
              - { color: "#008000", min: 721, max: 9999 } # Green
            title: "Cluster Age"
```

Then perhaps setting suffix to `h` would mean "human readable" and kromgo returns `3y64d` instead of `1159d` ???
