### ISSUE TITLE
Kromgo Panic when Metrics not available

### ISSUE THREAD

**Issue by reefland** [kashalls/kromgo#94]
I had an issue with my Ceph MGR stopped reporting some metrics, these metrics disappeared from Prometheus.  When calls came into kromgo for these metrics I got hard to understand panic message:

```
kromgo
version: v0.4.4 (4834ad6952d9daffe9c5198cda532af959631bca)
{"level":"info","ts":1739413594.5969095,"caller":"log/log.go:49","msg":"starting kromgo server","address":"0.0.0.0:80"}
{"level":"info","ts":1739413594.5969646,"caller":"log/log.go:49","msg":"starting health server","address":"0.0.0.0:8888"}
2025/02/13 02:29:24 http: panic serving 10.42.6.14:51924: runtime error: index out of range [0] with length 0
goroutine 75 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1947 +0xbe
panic({0xadd520?, 0xc00040c498?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/kashalls/kromgo/pkg/kromgo.(*KromgoHandler).ServeHTTP(0xc00015a230, {0xc1b6c0, 0xc000414620}, 0xc000409180)
	/build/pkg/kromgo/kromgo.go:105 +0x16e5
net/http.HandlerFunc.ServeHTTP(0xc0004180f0?, {0xc1b6c0?, 0xc000414620?}, 0xc000412624?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000119140, {0xc1b6c0, 0xc000414620}, 0xc000409180)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.0/mux.go:480 +0x2e2
net/http.HandlerFunc.ServeHTTP(0xc1c128?, {0xc1b6c0?, 0xc000414620?}, 0x105d8e0?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000119140, {0xc1b6c0, 0xc000414620}, 0xc000408f00)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.0/mux.go:90 +0x2ee
net/http.serverHandler.ServeHTTP({0xc0004049c0?}, {0xc1b6c0?, 0xc000414620?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc00040e990, {0xc1c0f0, 0xc00019f9e0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 18
	/usr/local/go/src/net/http/server.go:3360 +0x485
2025/02/13 02:29:54 http: panic serving 10.42.6.14:47376: runtime error: index out of range [0] with length 0
goroutine 145 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1947 +0xbe
panic({0xadd520?, 0xc00040c4c8?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/kashalls/kromgo/pkg/kromgo.(*KromgoHandler).ServeHTTP(0xc00015a230, {0xc1b6c0, 0xc00019cb60}, 0xc0001de280)
	/build/pkg/kromgo/kromgo.go:105 +0x16e5
net/http.HandlerFunc.ServeHTTP(0xc0000e83c0?, {0xc1b6c0?, 0xc00019cb60?}, 0xc0000acbd4?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000119140, {0xc1b6c0, 0xc00019cb60}, 0xc0001de280)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.0/mux.go:480 +0x2e2
net/http.HandlerFunc.ServeHTTP(0xc1c128?, {0xc1b6c0?, 0xc00019cb60?}, 0x105d8e0?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000119140, {0xc1b6c0, 0xc00019cb60}, 0xc0001de000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.0/mux.go:90 +0x2ee
net/http.serverHandler.ServeHTTP({0xc0001d4e10?}, {0xc1b6c0?, 0xc00019cb60?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0001a5560, {0xc1c0f0, 0xc00019f9e0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 18
	/usr/local/go/src/net/http/server.go:3360 +0x485
```

Hopefully you can have a way to trap something like this and show a message about the metric either not being available anymore or not returning a result.

Example of config items that stopped having metrics:
```
          - name: ceph_osd_up
            query: sum(ceph_osd_up{})
            colors:
              - {color: "silver", min: 0, max: 9999}
            title: "OSDs UP"

          - name: ceph_osd_in
            query: sum(ceph_osd_in{})
            colors:
              - {color: "silver", min: 0, max: 9999}
            title: "OSDs IN"

          - name: ceph_osd_out
            query: count(ceph_osd_up{}) - count(ceph_osd_in{})
            colors:
              - { color: "brightgreen", min: 0, max: 0 }
              - { color: "orange", min: 1, max: 3 }
              - { color: "red", min: 4, max: 9999 }
            title: "OSDs OUT"
```

As soon as I restarted the Ceph MGR, metrics scrapes happened and Prometheus metrics returned and kromgo operated as expected.
